### ISSUE TITLE
Breadcrumbs bug

### ISSUE THREAD

**Issue by delucis** [dn-m/dn-m.github.io#10]
This might be a one-off build error or something, but right now the breadcrumbs in [ArithmeticTools](http://dn-m.github.io/ArithmeticTools/index.html), [ArrayTools](http://dn-m.github.io/ArrayTools/index.html), and [CopyTools](http://dn-m.github.io/CopyTools/index.html) look to be broken:

![Broken breadcrumbs](https://cloud.githubusercontent.com/assets/357379/13727208/53484204-e8b7-11e5-93ad-bb6ea7818b4c.png)

This wasn’t the case before 7a921ee, so after the new templates, but I didn’t do anything that could conceivably have had this effect. Equally the bug is only in those three modules, so maybe it’s something happening with the data Jazzy is handling.

**Comment by jsbean** [comment]
Huh. Weird. :question:

**Comment by jsbean** [comment]
For only those three ([ArithmeticTools](http://dn-m.github.io/ArithmeticTools/index.html), [ArrayTools](http://dn-m.github.io/ArrayTools/index.html), and [CopyTools](http://dn-m.github.io/CopyTools/index.html)), this error shows itself:

`fatal: No names found, cannot describe anything.`

**Comment by delucis** [comment]
OK, so extra likelihood that its on the Jazzy side. Is that the error we were getting for the untagged frameworks?

**Comment by jsbean** [comment]
Which I thought was from the `git tag` version?

**Comment by jsbean** [comment]
Right, but they are all tagged...

**Comment by jsbean** [comment]
Yeah, they aren't getting the versions.

**Comment by jsbean** [comment]
I'm gonna push new tags for each to see if it clears up.

**Comment by jsbean** [comment]
All good now. I think I know what happened:

At some point when I ran the first version of the doc gen script with the accidental-grandparent path, it cleaned out those repos. So I pulled 'em all from `origin master`, which must not have retained `git tags`.

Which doesn't make total sense to me, but it's fine now :|.

**Comment by jsbean** [comment]
Go to bed.
