### ISSUE TITLE
Optimise dependency menu injection

### ISSUE THREAD

**Issue by delucis** [dn-m/dn-m.github.io#21]
If you accept #20, this follows as a logical enhancement.

Currently docs for all modules are processed by `InjectDependencies.rb` when `GenerateDocumentation.sh` is executed. A hash-stashing procedure similar to that implemented for the Jazzy routine should be implemented to avoid unnecessary repeat processing.

**Comment by jsbean** [comment]
Totally :+1: . 

Does this require creating another `hashstash` so that we have:
- `hashstash_jazzy`
- `hashstash_dependencies`

?

**Comment by delucis** [comment]
I think I can refactor the calling of `InjectDependencies.rb` to run from what is now the `build_docs()` function in `GenerateDocumentation.sh`. That would allow us to use the filtering that is already happening (`build_docs()` only gets called when the hashstash tests pass). Duplicating the logic seems a bad idea.
