### ISSUE TITLE
Flesh out main page

### ISSUE THREAD

**Issue by jsbean** [dn-m/dn-m.github.io#26]
Jazzy uses [Redcarpet](https://github.com/vmg/redcarpet) to parse the markdown formatted text in code comments, and for the READMEs.

Is it easy to implement this to parse a markdown file for the main page?

Files of interest from Jazzy are:
- [jazzy_markdown](https://github.com/realm/jazzy/blob/master/lib/jazzy/jazzy_markdown.rb)
- [readme_generator](https://github.com/realm/jazzy/blob/master/lib/jazzy/readme_generator.rb)

**Comment by delucis** [comment]
Taking a look at the Jazzy files, I would be tempted to implement something from scratch.

If I understand correctly, you want a markdown file — let’s call it `main.md` — that renders to the main content of `index.html` (where currently just “dn-m: Documentation for dn-m (dynamic notation for music)” is displayed).

The simplest approach might be:
1. Write `main.md`.
2. Process `main.md` to HTML but save it as `main.mo` (a mustache file).
3. Call `main.mo` in the `index.mo` template: `{{> main}}`.
4. That’s it. When we process `index.mo` in `GenerateFrontpage.sh` it will do everything we need.

So the only vaguely tricky step would be 2. There is even [a bash markdown renderer](https://github.com/chadbraunduin/markdown.bash), but for consistency it might be better to use Redcarpet, and also require Rouge if you need syntax highlighting on the front page.

**Comment by delucis** [comment]
If you accept #29, the next steps will be:
1. Implement syntax highlighting with `rouge`
2. Investigate exactly what the `redcarpet` options and extensions mean (lines 20–31 of `Md2Mo.rb`). I just yanked these from a demo.

**Comment by delucis** [comment]
Btw, #29 renders from `main.md` but given they are currently identical, you could also simply render from `README.md` if that was desirable. :thought_balloon:

**Comment by jsbean** [comment]
Yeah, I saw that. 

It could be worthwhile to have a separate github-specific README that may have contribution-focused thoughts. Whereas the site itself could be more of a clean API documentation.

**Comment by jsbean** [comment]
I think this is in a good place now. If want to integrate syntax highlighting, we can make that its own issue.
