### ISSUE TITLE
Consider using bundler for ruby dependency management

### ISSUE THREAD

**Issue by delucis** [dn-m/dn-m.github.io#27]
Given that `dn-m.github.io` now depends on both `jazzy` and `nokogiri`, consider using a [`Gemfile`](http://bundler.io/gemfile.html) and [`bundler`](http://bundler.io/) to facilitate dependency installation/management.
##### Example `Gemfile`

``` rb
source 'https://rubygems.org'
gem 'jazzy'
gem 'nokogiri'
```

Version specifiers are also an option.

With bundler installed (`gem install bundler`) getting all the dependencies ready would just need

``` sh
$ bundle install
```

**Comment by delucis** [comment]
This would be even more helpful if #26 becomes reality.

**Comment by jsbean** [comment]
I'll start poking at this.
