### ISSUE TITLE
Refactor to tidy root

### ISSUE THREAD

**Issue by delucis** [dn-m/dn-m.github.io#30]
The root is looking rather cluttered with among others
- **Shell:** `GenerateDocumentation.sh`, `GenerateFrontpage.sh`, `HandleDependencies.sh`
- **Ruby:** `InjectDependencies.rb`, `Md2Mo.rb`
- **Mustache:** `index.mo`, `main.mo`

I would suggest some refactoring to clean out the root moving things to `dependencies` or `build` for generated files.
##### Root could keep
- A master shell script: `build.sh`
- `index.html`
- `README.md`
- `LICENSE`
- `Gemfile` & `Gemfile.lock`
- _perhaps_ also `main.md` although that could equally go in `dependencies`
##### Redistribution
- shell scripts, ruby scripts, and `dependencies/mo` all move to `dependencies/scripts`
- mustache templates move to `dependencies/templates`
- if `main.md` gets moved, move to `dependencies/src`
- consider moving `dependencies/bean` to `dependencies/templates/bean`

Obviously this would all require rewriting of scripts to handle new path structures.

**Comment by jsbean** [comment]
I'm all for this.

Should we do it one directory refactoring at a time, along with the requisite change in script?

**Comment by delucis** [comment]
It’s a little tricky to untangle, because it’s all interrelated. Perhaps starting with moving the templates makes sense though?

**Comment by jsbean** [comment]
I think that's good: how about I start a branch for this?

Start with `bean` --> `dependencies/templates/bean`: change `GenerateDocumentation.sh`. Any other fallout from that change?

**Comment by delucis** [comment]
No, I think that’s the only place that path gets invoked.
