### ISSUE TITLE
Where does MusicXML fits in the dependency tree?

### ISSUE THREAD

**Issue by DJBen** [dn-m/dn-m.github.io#40]
I am in awe of the organization of these packages and projects, wondering how does the MusicXML play in the role of the dependencies?

**Comment by jsbean** [comment]
Hi @DJBen! 

The [`MusicXML`](https://github.com/dn-m/MusicXML) package is designed to be self-contained (that is, outside of the `dn-m` dependency graph). It's just a one-to-one mapping of the `musicXML` [specification](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#XS-MusicXML.htm%3FTocPath%3DMusicXML%2520Reference%7CScore%2520Schema%2520(XSD)%7C_____0): anyone can traverse it and convert it to whatever model they desire, extracting the bits they want and discarding the rest.

While there is quite a bit of potential overlap with other types defined in packages like [`Music`](https://github.com/dn-m/Music), [`NotationModel`](https://github.com/dn-m/NotationModel), and the like, there was enough of a difference between how I'd want to represent these types than how they are represented in musicXML that I felt it best to keep 'em separated.

Even for the `dn-m` project, I'll add an adapter layer to massage the musicXML tree into the desired intermediate representation.

What are you trying to do? Let me know if you've had any difficulties getting any of the packages up and running!

**Comment by DJBen** [comment]
Hi James,

Thank you for your speedy reply.

I am making a score renderer (with limited domain to maybe single part only) that can accept commonly exchanged format like `musicXML` using a SMuFL-compliant font. I have some special needs to animate the notes and such, and the existing solutions on git are either very outdated, or does not work with Swift, so I decide to create my own.

I definitely feels the same as you do that `musicXML` is not great for human to construct or to read if we want to generate the score in a declarative way, I feel that it's neither good for rendering. I wander into the `NotationModel` and `NotationView` projects, and found they are not suitable for my goal for the few reasons (from my perspective)
- They are generating the score by intepreting `Music` models. I think it is great to generate notations directly from the most ideal representation. The tradeoff is the sacrifice of ease of format exchange.
- They are making out visual components by generating visual primitives, rather than using SMuFL fonts. (I might be wrong) 
- They are still in the early stages.

Apparently you have explored much deeper in this area than I have ever done. Could you offer any pointers regarding which libraries / tools should I use best? Would appreciate your input!

**Comment by jsbean** [comment]
> They are making out visual components by generating visual primitives, rather than using SMuFL fonts. (I might be wrong)

Yes, this is true currently, though not aspirationally 😅. It is very high up in my queue to use SMuFL fonts primarily, though I haven't stumbled upon a cross-platform font / text renderer. For now, I would imagine that using `CoreText` is the best way to handle Apple platforms. If you have any thoughts on that front, that would be amazing.

Regarding other libraries, I would look into:

- [MusicNotationCore](https://github.com/drumnkyle/music-notation-core) / [MusicNotationKit](https://github.com/drumnkyle/music-notation-kit), another early-development Swift project
- [Verovio](https://github.com/rism-ch/verovio), a relatively young C++ library with Javascript bindings, but active in development
- [Guido](https://github.com/grame-cncm/guidolib), a mature C++ library that has a `CoreGraphics` backend

I would be _very_ interested in developing an open Swift SMuFL renderer with various backends, especially if it doesn't cut off compatibility with Linux down-the-road.

Let's keep this conversation going regarding any of these concepts. Send me an email (the one in my profile is legit). We can move this to Slack.

**Comment by jsbean** [comment]
@DJBen, I'm going to close this. This conversation is surely one to keep having in various venues!
